services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
      
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1234
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin1234@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"

  apiimage1:
    build: .
    image: api-image:1.0.0
    ports:
      - 4500:3006
    environment:
      PORT: 3006
      MONGO_URL: mongodb://admin:admin1234@mongodb:27017/producto?authSource=admin